# Generated by Django 2.0.3 on 2018-04-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudvehicles', '0003_auto_20180331_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='name',
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
